config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'main#index'
  post '/search' => 'main#search'
  get '/picklist' => 'main#picklist'
  post '/addrestaurant' => 'restaurants#create'
  
  resources :lists, :restaurants

end

app/models/list.rb
# == Schema Information
#
# Table name: lists
#
#  id             :integer          not null, primary key
#  name           :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  user_id        :integer
#  restaurants_id :integer
#

class List < ActiveRecord::Base
  belongs_to :user
  has_many :memberships, :dependent => :destroy
  has_many :restaurants, :through => :memberships
  #delegate :restaurants, :to => :memberships
end

app/models/membership.rb
# == Schema Information
#
# Table name: memberships
#
#  id            :integer          not null, primary key
#  restaurant_id :integer
#  list_id       :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Membership < ActiveRecord::Base
	belongs_to :restaurant
	belongs_to :list
end

app/models/restaurant.rb
# == Schema Information
#
# Table name: restaurants
#
#  id             :integer          not null, primary key
#  name           :string
#  link           :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  yelp_id        :string
#  list_id        :integer
#  listname       :string
#  image_url      :string
#  address        :string
#  rating_img_url :string
#  review_count   :integer
#

class Restaurant < ActiveRecord::Base
	has_many :memberships, :dependent => :destroy
	has_many :lists, :through => :memberships
	#delegate :lists, :to => :memberships
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  password               :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  name                   :string
#  lists_id               :integer
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  #validates :name, :presence=>true, :length=> {:minimum=>3}, :uniqueness=>true
  #validates :password, :presence=>true, :length=>{:minimum=>6}
  has_many :lists, -> { order(created_at: :desc) }, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :name, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password) }
  end
  
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
  	@list = List.new
  end

  def create
  	@list = List.new(list_params)
    @list.user = current_user
  	if @list.save!
  		redirect_to :action => 'new'
  	else
  		redirect_to :action => 'new'
  	end
  end

  def index
  	@lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def edit
    @list = List.find(params[:id])
  end

  def find_users(user)
    @list = List.where(user: user)
  end

  def find_restaurants(restaurant)
    @list = List.where(restaurant: restaurant)
  end

  def update(user)
    @list = List.find(user: user)
    if @list.update_attributes(list_params)
      redirect_to list_path(@list.id)
    else
      render 'edit'
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to :action => 'new'
  end

  private

  def list_params
  	params.require(:list).permit(:name)
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
  	@user = current_user
  end

  def picklist
    @list =  List.where(:name => params[:name]).first
    render json: @list.to_json(:include => :restaurants)
  end

  def search
    parameters = { term: 'food', limit: 20, offset: params[:offset]}
    render json: Yelp.client.search(params[:city], parameters)
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def new
  	@restaurant = Restaurant.new
  end

  def create
    if Restaurant.where(:yelp_id => params[:yelp_id]).blank?
    	@restaurant = Restaurant.new(restaurant_params)
      @restaurant.lists << current_user.lists.where(:name => params[:listname]).first
    	@restaurant.save
    else
      @restaurant = Restaurant.where(:yelp_id => params[:yelp_id]).first
      @restaurant.lists << current_user.lists.where(:name => params[:listname]).first
    end
    redirect_to root_path
  end

  def index
  	@restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update_attributes(restaurant_params)
      redirect_to restaurant_path(@restaurant.id)
    else
      render 'edit'
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
  	params.permit(:name, :link, :yelp_id, :image_url, :address, :rating_img_url, :review_count, :listname)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save!
  		redirect_to users_path
  	else
  		render 'new'
  	end
  end

  def index
  	@users = User.all
  end

  def show
    @user = current_user
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_path(@user.id)
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
  	params.require(:user).permit(:name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_sidebar.html.erb
<div id="sidebar">
	<div id="editprofile" class="sidebar_text">
		<%= link_to edit_user_registration_path do%>
			<p>Hi, <%= current_user.name%></p>
		<%end%>
	</div>
	<div id="pick" class="sidebar_text"> 
		<h1><%= link_to "PICK", root_path%></h1> 
	</div>
	<div id="managelists" class="sidebar_text">
		<%= link_to "Manage Lists", new_list_path%>
	</div>
	<div class="sidebar_text">
		<%= link_to "Logout", destroy_user_session_path, method: :delete%>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YouPick</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "application", '//fonts.googleapis.com/css?family=Varela Round', :media => "all" %>
  <%= stylesheet_link_tag "application", '//fonts.googleapis.com/css?family=Dosis', :media => "all" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
  <%= render "layouts/sidebar" %>
	<div id="mainspace">
		<%= yield %>
	</div>
<% else %>
	<%= yield %>
<% end %>


</body>
</html>

app/views/lists/edit.html.erb
<h1>&nbsp;Lists#edit</h1>
<%= form_for(@list) do |f| %> 
    <div class="field">
        <p>&nbsp;&nbsp;name</p> 
        &nbsp;&nbsp;<%= f.text_field :name%> 
    </div> 
    <div class="actions"> 
    	&nbsp;&nbsp;<%= f.submit %> 
    </div> 
<% end %>

<%= link_to "Back to Main", root_path%>

app/views/lists/index.html.erb
<h1>Lists#index</h1>
<table> 
	<tr>
		<td>name</td> 
	</tr> 
	<% @lists.each do |list| %> 
		<tr> 
			<td> <%= link_to list.name, list_path(list.id)%></td>
		</tr> 
	<% end %> 
</table>

<%= link_to "Add new list", new_list_path%>
<%= link_to "Back to Main", root_path%>

app/views/lists/new.html.erb
<%= javascript_tag do %>
	$(".sidebar_text a").removeClass("current");
	$("#managelists a").addClass("current");
<% end %>

<p class="pagename">My Lists</p>
<%= @list.errors.full_messages.first if @list.errors.any? %>
<%= form_for(@list) do |f| %> 
    <div class="field inline">
        <p class="field">Name&nbsp;&nbsp;&nbsp;
        	<%= f.text_field :name%>
        </p> 
    </div> 
    <div id="addlist" class="actions inline"> 
    	<%= f.submit %> 
    </div> 
<% end %>

<div id="showlists" class="field">
	<%= render "users/show"%>
</div>

app/views/lists/show.html.erb
<div>
	<h2><%= @list.name%></h2>
</div>

<%= link_to "edit list", edit_list_path(@list.id)%>
<%= button_to "destory list", @list, method: :delete %>

app/views/main/index.html.erb
<% if !user_signed_in? %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

<%= javascript_tag do %>
	$(".sidebar_text a").removeClass("current");
	$("#pick a").addClass("current");
<% end %>

<div id="location">
	<div class="field">
		<p>Please enter your current city: </p>
	    <%= text_field_tag "city", nil, :id => "cityvalue" %>
	</div>
    <div class="actions">
        <%= button_tag "Enter", :id => "citybutton" %>
    </div>
</div>
<div id="listchoicebox" class="hide field">
	<p class="inline">Choose from:&nbsp;&nbsp;</p>
	<%= collection_select(:restaurant, :list_id, current_user.lists, :id, :name, {:prompt => "All results"}, {:id => "pickchoice"})%>
</div>
<div id="pickspace"></div>
<div id="pickagainbox" class="hide field">
	<p class="inline">Add to list:&nbsp;&nbsp;</p>
	<%= collection_select(:restaurant, :list_id, current_user.lists, :id, :name, {}, {:id => "addchoice"}) %>
	<%= button_tag "Enter", :id => "addtolistbutton" %>
	<div><%= button_tag "Pick Again", :id => "pickagainbutton" %></div>
</div>

app/views/notifications/forgot_password.html.erb
<h1>Notifications#forgot_password</h1>

<p>
  <%= @greeting %>, find me in app/views/notifications/forgot_password.html.erb
</p>

app/views/notifications/forgot_password.text.erb
Notifications#forgot_password

<%= @greeting %> <%= @name %>, your password was <%= @password %>.

app/views/restaurants/edit.html.erb
<h1>Restaurants#edit</h1>
<%= form_for(@restaurant) do |f| %> 
    <div class="field">
        <p>&nbsp;&nbsp;name</p> 
        &nbsp;&nbsp;<%= f.text_field :name%>
    </div>
    <div class="field">
        <p>&nbsp;&nbsp;link</p>
        &nbsp;&nbsp;<%= f.text_field :link%>
    </div>
    <div class="actions">
        &nbsp;&nbsp;<%=f.submit%>
    </div>
<% end %>

<%= link_to "Back to Main", root_path%>

app/views/restaurants/index.html.erb
<h1>Restaurants#index</h1>
<table> 
	<tr>
		<td>name</td> 
		<td>link</td> 
	</tr> 
	<% @restaurants.each do |restaurant| %> 
		<tr> 
			<td> <%= link_to restaurant.name, restaurant_path(restaurant.id)%></td> 
			<td><%= restaurant.link %></td> 
		</tr> 
	<% end %> 
</table>

<%= link_to "Add new restaurant", new_restaurant_path%>
<%= link_to "Back to Main", root_path%>

app/views/restaurants/new.html.erb
<h1>Restaurants#new</h1>
<%= form_for(@restaurant) do |f| %> 
    <div class="field">
        <p>name</p> 
        <%= f.text_field :name%> 
    </div> 
    <div class="field"> 
    	<p>link</p> 
    	<%= f.text_field :link%> 
    </div> 
    <div class="actions"> 
    	<%= f.submit %> 
    </div> 
<% end %>

app/views/restaurants/show.html.erb
<h1>Restaurants#show</h1>

<div>
	<h2><%= @restaurant.name%></h2>
	<p><%=@restaurant.link%></p>
</div>

<%= link_to "edit restaurant", edit_restaurant_path(@restaurant.id)%>
<%= button_to "destory restaurant", @restaurant, method: :delete %>
<%= link_to "Back to Main", root_path%>

app/views/users/_show.html.erb
<%if current_user.lists.empty?%>
	<p class="gray">You have no lists!</p>
<%else%>
	<% current_user.lists.each do |list|%>
		<div class="list">
			<table>
			<th><%=list.name%></th>
			<%if list.restaurants.empty?%>
				<tr><td>This list is empty!</td></tr>
			<%else%>
				<% list.restaurants.each do |restaurant|%>
					<tr><td><%=link_to "#{restaurant.name}", "#{restaurant.link}", target: ":_blank"%></td></tr>
				<%end%>
			<%end%>
			</table>
			<div class="deletebutton">
				<%= button_to "Delete List", list, method: :delete, controller: "list" %>
			</div>
			<div class="clear"></div>
		</div>
	<%end%>
<%end%>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<%= form_for(@user) do |f| %>
    <div class="field">
        <p>&nbsp;&nbsp;name</p> 
        &nbsp;&nbsp;<%= f.text_field :name%>
    </div>
    <div class="field">
    	<p>&nbsp;&nbsp;email</p>
    	&nbsp;&nbsp;<%= f.text_field :email%>
    </div>
    <div class="field">
    	<p>&nbsp;&nbsp;password</p>
    	&nbsp;&nbsp;<%= f.text_field :password%>
    </div>

    <br>

    <div class="actions">
    	&nbsp;&nbsp;<%=f.submit%>
    </div>
<% end %>

<%= link_to "Back to Main", root_path%>

app/views/users/index.html.erb
<h1>Users#index</h1>
<table>
	<tr>
		<td>name</td>
		<td>email</td>
		<td>password</td>
	</tr>
	<% @users.each do |user| %>
		<tr>
			<td> <%= link_to user.name, user_path(user.id)%></td>
			<td> <%= user.email %></td>
			<td> <%= user.password %></td>
		</tr>
	<% end %>
</table>

<%= link_to "Add new user", new_user_path%>
<%= link_to "Back to Main", root_path%>

app/views/users/new.html.erb
<h1>&nbsp;Users#new</h1>
<%= form_for(@user) do |f| %>
    <div class="field">
        <p>&nbsp;&nbsp;name</p> 
        &nbsp;&nbsp;<%= f.text_field :name%>
    </div>
    <div class="field">
        <p>&nbsp;&nbsp;email</p>
        &nbsp;&nbsp;<%= f.text_field :email%>
    </div>
    <div class="field">
        <p>&nbsp;&nbsp;password</p>
        &nbsp;&nbsp;<%= f.text_field :password%>
    </div>

    <br>

    <div class="actions">
        &nbsp;&nbsp;<%=f.submit%>
    </div>
<% end %>

<%= link_to "Back to Main", root_path%>